version: '3.4'

services:
    consul:
        image: consul:${TAG:-latest}
        command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
        hostname: consul
        container_name: consul
        networks:
            - consul-network
        restart: always
        ports:
        - "8500:8500"
        
networks:
   consul-network:
        # external: 
        #     name: docker_consul-network