version: '3'

networks:
  neo4j-network:
    driver: bridge

services:
  neo4j:
    image: bitnami/neo4j:latest
    container_name: neo4j-local
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
    - data:/bitnami
    environment:
        - NEO4J_PASSWORD=t0ps3cr3tt0ps3cr3t
        - NEO4J_BOLT_PORT_NUMBER=7687
        - NEO4J_HTTP_PORT_NUMBER=7474
        - NEO4J_HTTPS_PORT_NUMBER=7473
volumes:
  data:
# version: "3.2"
# services:
#   neo4j:
#     image: neo4j:latest
#     container_name: 'dev-neo4j'
#     volumes:
#       - './neo4j/data:/data'
#       - './neo4j/logs:/logs'
#       - './neo4j/import:/var/lib/neo4j/import'

#     ports:
#       - 7473:7473
#       - 7474:7474
#       - 7687:7687
#     restart: always
#     networks:
#         - neo4j_network
#     environment:
#       NEO4J_AUTH: neo4j/t0ps3cr3tt0ps3cr3t

# networks:
#   neo4j_network:
#     driver: bridge


# version: "3.8"

# services:
#   neo4j:
#     image: neo4j:latest
#     container_name: neo4j
#     environment:
#       - NEO4J_AUTH=neo4j/thuong@123
#       - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
#     ports:
#       - "7474:7474"
#       - "7687:7687"
#     volumes:
#       - neo4j_data:/data
#       - neo4j_logs:/logs
#       - neo4j_import:/import

# volumes:
#   neo4j_data:
#   neo4j_logs:
#   neo4j_import: