version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thuong@123
      MYSQL_DATABASE: chatdb
      MYSQL_USER: thuongnguyen
      MYSQL_PASSWORD: thuong@123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: thuong@123
    ports:
      - 8080:80
    networks:
      - mysql-network

networks:
   mysql-network:
        driver: bridge